import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { GraphQLClient, gql } from 'graphql-request'
import BlogCard from '../components/BlogCard'

const graphcms = new GraphQLClient('https://api-ap-northeast-1.graphcms.com/v2/cl43qiy2l5nds01xj7gjnbl2q/master');

const QUERY = gql`
  {
    posts{
      slug
      author {
        name,
        avatar {
          url
        }
      }
      date_published
      title
      coverPhoto{
        url
      }
    }
  }
`

export async function getStaticProps(){
  const {posts} = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate:10,
  };
}

export default function Home({posts}) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className ={styles.main}>
        {posts.map((post) => (
          <BlogCard title={post.title} slug = {post.slug} author={post.author} coverPhoto = {post.coverPhoto} datePublished = {post.date_published}/>
        ))}
      </main>
    </div>
  )
}
